### ISSUE TITLE
Proper way to use it on ngx lua resty

### ISSUE THREAD

**Issue by leandromoreira** [dream11/lua-circuit-breaker#18]
Looking at the source code, it seems that the lib uses local state to keep the counters, which, I think, reflects on a per-worker basis on ngx.resty environment, is that right?

Do you have any examples/good practices about using it on nginx / lua? (should one use ngx.shared as storage for the Counters) what should be created on init or globably?

```nginx
events {
  worker_connections 1024;
}

error_log stderr;

http {
  init_by_lua_block {
    local circuit_breaker_lib = require "lua-circuit-breaker.factory"
    circuit_breakers = circuit_breaker_lib:new() -- is it necessary to globably create this?
    -- or can we create for each request?
  }

  server {
    listen 8080;

    location /lua_content {
      content_by_lua_block {
        local settings = {} --all settings
        local cb, err = circuit_breakers:get_circuit_breaker(
            "io_call_x", -- Name of circuit breaker. This should be unique.
            "io_calls", -- Used to group certain CB objects into one.
            settings,
           )


          local _, err_cb = cb:_before()
          if err_cb then
              ngx.exit(504)
              return
          end
          local generation = cb._generation
          local res, err_http = makeIOCall()
          
          local ok = res and res.status and res.status < 500
          cb:_after(generation, ok)
      }
    }
  }
}
```

**Comment by leandromoreira** [comment]
If such good practices, recomendation exist, it may be useful to document it. What are you thoughts?

**Comment by leandromoreira** [comment]
or maybe using lua modules to `load` the `circuit_breakers`?
```lua
local module = {}

local circuit_breaker_lib = require "lua-circuit-breaker.factory"
local circuit_breakers = circuit_breaker_lib:new()

module.circuit_breakers = circuit_breakers

return module
```

**Comment by chirag-manwani** [comment]
> Looking at the source code, it seems that the lib uses local state to keep the counters, which, I think, reflects on a per-worker basis on ngx.resty environment, is that right?

Yes, the counters are local but it totally depends on you on how you want to use the _circuit-breaker_ instance returned by the new method in factory.lua. In our use case, we wanted per-worker circuit breakers so we stored them as local variables. 
 
> Do you have any examples/good practices about using it on nginx / lua? (should one use ngx.shared as storage for the Counters) what should be created on init or globally?

I think you could face some race conditions if the workers try to read and update the counters at the same time, so having per-worker copies of a circuit-breaker should work better. 

>   init_by_lua_block {
>     local circuit_breaker_lib = require "lua-circuit-breaker.factory"
>     circuit_breakers = circuit_breaker_lib:new() -- is it necessary to globably create this?
>     -- or can we create for each request?
>   }

The circuit breaker object needs to persist across requests, so it should not be per request.

**Comment by chirag-manwani** [comment]
> or maybe using lua modules to `load` the `circuit_breakers`?
> 
> ```lua
> local module = {}
> 
> local circuit_breaker_lib = require "lua-circuit-breaker.factory"
> local circuit_breakers = circuit_breaker_lib:new()
> 
> module.circuit_breakers = circuit_breakers
> 
> return module
> ```

Yes, I think this would be the best way to do it. The documentation recommends doing it this way too. https://github.com/openresty/lua-nginx-module#data-sharing-within-an-nginx-worker

A PR would for this change is highly welcome.

**Comment by leandromoreira** [comment]
Thanks @chirag-manwani I was thinking to provide a full-fledge nginx lua example, [kinda of a docker playground (I prototyped a quick version)](https://github.com/leandromoreira/lua-circuit-breaker/tree/master/ngx_lua_sample). What do you think?

**Comment by chirag-manwani** [comment]
@leandromoreira This looks great!
So anyone wanting to use the circuit-breaker manager object, will themselves create a module and use it. I think this should work out well.

**Comment by leandromoreira** [comment]
:) thanks @chirag-manwani do you want me to do a PR from that `ngx_sample_code` in here?

**Comment by chirag-manwani** [comment]
Yes please do. Also, I think we should include this usage somewhere in the root level README as well. We could create a subsection in the Sample Usage section and point to the directory you created.
